### ISSUE TITLE
commit to source rather than master

### ISSUE THREAD

**Issue by krazedkrish** [chautari-space/chautari-space.github.io#1]
Hi Avash, I see that you have committed in master branch. I suggest you modify the source instead. Because, master branch is actaully generated from source branch. So, your commits are lost when some one else modifies it. All you need to do is add the  photo in theme static img folder  and then update the config.toml. the rest are included in read me.

by the way you can add info for rohit bahadur thapa, and others who i missed . atleast the name.

**Comment by Avasz** [comment]
eh ok.
